"""Fun-Shirt-Sprueche: kurze, witzige deutsche Sprueche mit einem kleinen passenden Motiv.

Vorgabe des Betreibers (17.09.2026): Der Shop fokussiert sich auf GENAU diese
Nische. Jeder Eintrag ist Spruch zuerst, das Motiv bleibt klein und dient dem
Spruch, statt ihn zu erschlagen - typischer Fun-Shirt-Stil.

Ueberarbeitung (18.09.2026): Die erste Fassung mit 204 Spruechen war dem Betreiber
zu mittelmaessig. Neu: deutlich mehr Witz und eigene Pointen statt Standardsaetzen,
gut lesbare Druckschrift statt Schreibschrift, Schrift immer weiss (auf dem weissen
Shirt schwarz, siehe ``postprocess/schriftfarbe.py``). Das Motiv verwendet daher
kein Weiss.

Die Eintraege laufen durch dieselbe Qualitaets- und Rechtepruefung wie die
Websuche (``trends.speichere``): keine Marken, keine Zitate, kein Copy-Paste.
Laden kostet nichts; Geld kostet erst "Motiv erzeugen".
"""
from __future__ import annotations

from datetime import date
from typing import Any, Callable

from app.studio.radar import trends

KATEGORIE = "funshirt"

_STIL = ("Minimalistischer realistischer Siebdruck-Look: der Spruch gross und zentral in "
         "kraeftiger, gut lesbarer Druckschrift (serifenlose Blockschrift in Versalien, "
         "keine Schreib- oder Handschrift), Schrift reinweiss, das Motiv klein darunter "
         "und dem Spruch klar untergeordnet, viel Freiraum, hoechstens zwei Motivfarben "
         "ohne Weiss")
_DRUCK = ("Spruch und Motiv als eine geschlossene freigestellte Einheit mit kraeftigen "
          "Konturen, keine feinen Verlaeufe; weisse Schrift fuer dunkle Shirts, fuer das "
          "weisse Shirt entsteht daraus automatisch eine Fassung mit schwarzer Schrift")
_RISIKO = "Vor dem Einstellen pruefen, dass der Spruch nicht mit einem bekannten Zitat kollidiert"
_ZEITRAUM = "Immergruen, Spitzen zu Geburtstagen, Feiertagen und als Spontankauf"
_WARUM = ("Fun-Shirts mit Spruch sind ein dauerhaft gefragtes Geschenksegment; eine "
          "ueberraschende Pointe wird geteilt und verschenkt, ein kleines eigenes Motiv "
          "macht den Spruch zum Blickfang statt zum reinen Textdruck.")
_PRODUKT = "T-Shirt, alternativ Hoodie oder Tasse"
_KAUFMOMENT = ("Spontankauf oder Geschenk, wenn sich jemand im Spruch sofort wiedererkennt "
               "und laut lachen muss")

# Je Eintrag: (thema, spruch, kleines motiv, zielgruppe, suchwort, motivfarben)
# Regeln: Spruch hoechstens 8 Woerter, eigene Pointe, keine Marke, kein bekanntes Zitat.
_Eintrag = tuple[str, str, str, str, str, str]

_GRUPPEN: tuple[tuple[str, tuple[_Eintrag, ...]], ...] = (
    ("Alltag", (
        ("Kaffee-Charakter", "Erst Kaffee, dann Charakter.", "dampfende Kaffeetasse",
         "Morgenmuffel, die ohne Kaffee nicht ansprechbar sind", "Kaffee", "Kaffeebraun, Senfgelb"),
        ("Montags-Vorurteil", "Montag ist nur ein Dienstag mit Vorurteilen.", "Kalenderblatt mit Fragezeichen",
         "Berufstätige mit trockenem Humor über den Wochenstart", "Montag", "Signalrot, Anthrazit"),
        ("Sofa-Beziehung", "Mein Sofa und ich: Eine Langzeitbeziehung.", "Herz auf einem Sofakissen",
         "Serienfans, die das Wochenende bewusst faul verbringen", "Sofa", "Rosa, Anthrazit"),
        ("Wecker-Verhandlung", "Der Wecker klingelte. Ich habe verhandelt.", "kleiner Wecker mit Schweißtropfen",
         "Langschläfer, die jeden Morgen mit dem Wecker feilschen", "Wecker", "Rot, Anthrazit"),
        ("Akku-Solidarität", "Akku bei 2 Prozent. Wie ich.", "fast leere Batterie",
         "Erschöpfte Berufstätige mit Sinn für Selbstironie", "Akku", "Rot, Gelb"),
        ("Chaos-Freiheit", "Chaos ist nur Ordnung mit Freiheitsdrang.", "schiefer Zettelstapel",
         "Chaotische Organisationstalente mit Selbstironie", "Chaos", "Türkis, Senfgelb"),
        ("Wäscheberg-Wanderweg", "Der Wäscheberg hat jetzt Wanderwege.", "kleiner Berg aus Wäschestücken mit Fahne",
         "Haushaltsgeplagte mit Humor für den Wäscheberg", "Wäsche", "Blau, Rot"),
        ("Kühlschrank-Enttäuschung", "Kühlschrank auf. Kühlschrank zu. Enttäuschung.", "offener Kühlschrank mit leerem Fach",
         "Hungrige Heimkehrer, die zum dritten Mal nachsehen", "Kühlschrank", "Türkis, Gelb"),
        ("Pünktlich-Ungefähr", "Ich komme gleich. Also bald. Ungefähr.", "kleine Sanduhr mit Fragezeichen",
         "Notorische Zuspätkommer mit Selbstironie", "Zuspätkommer", "Orange, Anthrazit"),
        ("Internet-Mensch", "Ohne Internet bin ich nur ein Mensch.", "kleines Wlan-Symbol mit Sorgenfalte",
         "Digital abhängige Berufstätige mit Humor", "Internet", "Blau, Grün"),
        ("Vorsatz-Sport", "Mein Sport: Vorsätze fassen.", "kleine Hantel mit Schleife",
         "Menschen, die jedes Jahr mehr Sport vorhaben", "Sport", "Rot, Anthrazit"),
        ("Diät-Montag", "Diät startet Montag. Welcher, ist offen.", "kleine Waage mit Keks",
         "Genussmenschen mit Diät-Selbstironie", "Diät", "Grün, Braun"),
        ("Brot-Kanu", "Wollte nur Brot. Kam mit Kanu heim.", "kleines Kanu mit Brot",
         "Spontankäufer, die im Laden immer mehr mitnehmen", "Einkaufen", "Braun, Blau"),
        ("Passwort-Kreativität", "Passwort vergessen. Dabei war es so kreativ.", "kleines Schloss mit Schlüsselloch-Gesicht",
         "Digitale Vergesslichkeit als Alltagsscherz für Berufstätige", "Passwort", "Gold, Anthrazit"),
        ("Parkplatz-Glück", "Parkplatz gefunden. Leben gelingt.", "kleines Auto mit Sternchen",
         "Autofahrer in der Großstadt mit Parkplatznot", "Parkplatz", "Gelb, Anthrazit"),
        ("Ausrede-Meister", "Nicht vergessen. Nur strategisch aufgeschoben.", "kleine Kalenderseite mit Loch",
         "Aufschieber mit Sinn für Selbstironie", "Aufschieber", "Orange, Anthrazit"),
        ("Perfekt-Nur-Nicht-Heute", "Ich bin perfekt. Nur nicht heute.", "kleiner Stern mit Kratzer",
         "Selbstironische Perfektionisten mit Humor", "Perfektionist", "Gold, Anthrazit"),
        ("Ab-11-Uhr", "Ich funktioniere ab 11 Uhr.", "kleine Uhr auf elf Uhr",
         "Morgenmuffel, die erst spät am Vormittag ansprechbar sind", "Morgenmuffel", "Blau, Gelb"),
        ("Sarkasmus-Muttersprache", "Sarkasmus ist meine Muttersprache.", "kleine Sprechblase mit Augenbraue",
         "Menschen mit trockenem, sarkastischem Humor", "Sarkasmus", "Anthrazit, Senfgelb"),
        ("Menschen-Dosis", "Ich mag Menschen. In kleinen Dosen.", "kleine Tablette mit Herz",
         "Introvertierte mit Sinn für Selbstironie", "Introvertiert", "Rot, Anthrazit"),
        ("Sofort-Nur-Nicht", "Ich kann alles. Nur nicht sofort.", "kleine Schnecke mit Krone",
         "Gelassene Aufschieber mit Selbstironie", "Aufschieber", "Grün, Gelb"),
        ("Stur-Gründlich", "Nicht stur. Nur gründlich im Recht.", "kleiner Zeigefinger mit Haken",
         "Rechthaber mit Humor über die eigene Sturheit", "Rechthaber", "Rot, Anthrazit"),
        ("Nachtschicht-Gedanken", "Beste Ideen kommen um drei Uhr nachts.", "kleine Glühbirne mit Schlafmütze",
         "Nachtmenschen, die nachts die besten Ideen haben", "Nachteule", "Gelb, Dunkelblau"),
        ("Update-Ich", "Update verfügbar: Ich, aber besser.", "kleiner Ladebalken mit Pfeil",
         "Selbstoptimierer mit Humor über die eigenen Vorsätze", "Update", "Türkis, Anthrazit"),
        ("Aufräum-Everest", "Wäsche gefaltet: Mein Everest.", "kleiner Wäschestapel mit Bergfahne",
         "Haushaltsgeplagte mit Humor über Alltagsarbeit", "Wäsche", "Blau, Gelb"),
        ("Nur-Kurz", "Ich lade nur kurz mein Handy. Und mich.", "kleines Handy mit Steckdose",
         "Erschöpfte mit Sinn für Alltagshumor", "Handy", "Grün, Anthrazit"),
        ("Cent-Snack", "Ich spare mein Geld. Für Snacks.", "kleines Sparschwein mit Chips",
         "Snack-Fans mit Humor über ihr Budget", "Snack", "Rosa, Gelb"),
        ("Schlaf-Leistungskader", "Schlafen: Mein Hobby im Leistungskader.", "kleine Medaille mit Kissen",
         "Langschläfer mit Sinn für Selbstironie", "Schlafen", "Gold, Dunkelblau"),
    )),
    ("Familie", (
        ("Papa-Werkzeug", "Papa kann alles. Zumindest hat er Werkzeug.", "kleiner Schraubenschlüssel mit Herz",
         "Kinder und Partner, die Papas Bastellust liebevoll aufziehen", "Papa", "Orange, Anthrazit"),
        ("Papa-Witze", "Papa-Witze sind mein Beruf.", "kleine Sprechblase mit Krone",
         "Väter mit Vorliebe für schlechte Witze", "Papa", "Gelb, Anthrazit"),
        ("Papa-Grill", "Papa am Grill: Ehre und Feuer.", "kleine Grillzange mit Flamme",
         "Väter, die den Grill als Chefsache sehen", "Papa Grill", "Rot, Anthrazit"),
        ("Mama-Wissen", "Mama weiß alles. Auch was du verschweigst.", "kleines Auge mit Herz",
         "Kinder, die ihrer allwissenden Mama ein Denkmal setzen", "Mama", "Rosa, Anthrazit"),
        ("Mama-Feierabend", "Mama-Modus: Immer im Dienst.", "kleiner Kaffeebecher mit Sorgenfalte",
         "Mütter mit Selbstironie über den Familienalltag", "Mama", "Rosa, Braun"),
        ("Mama-Kekse", "Mama hat Augen im Hinterkopf. Und Kekse.", "kleiner Keks mit Auge",
         "Kinder, die Mamas Aufmerksamkeit liebevoll aufziehen", "Mama", "Braun, Rosa"),
        ("Oma-Nachschlag", "Bei Oma gibt es nur Nachschlag.", "kleiner Kochtopf mit Herz",
         "Enkel, die Omas Kochkünste feiern", "Oma", "Rot, Gelb"),
        ("Oma-Königin", "Oma ist die Königin der Kekse.", "kleine Krone mit Keks",
         "Enkel, die ihre Oma als Königin der Kekse verehren", "Oma", "Gold, Rosa"),
        ("Opa-Werkstatt", "Opas Werkstatt: Wo Ordnung verhandelbar ist.", "kleiner Hammer mit Schraube",
         "Enkel, die Opas Werkstatt und seine Ordnung lieben", "Opa", "Braun, Orange"),
        ("Opa-Geschichten", "Opa erzählt. Jedes Mal besser.", "kleiner Sessel mit Sprechblase",
         "Enkel, die Opas Geschichten liebevoll aufziehen", "Opa", "Braun, Grün"),
        ("Eltern-Schlaf", "Eltern: Profis im Schlafmangel.", "kleines Kissen mit Fragezeichen",
         "Müde Eltern mit Humor über ihre Nachtruhe", "Eltern", "Blau, Gelb"),
        ("Geschwister-Auswahl", "Geschwister: Freunde, die man nicht aussuchen darf.", "kleine Sanduhr mit zwei Herzen",
         "Geschwister mit Humor über ihre besondere Bindung", "Geschwister", "Rot, Türkis"),
        ("Lieblingstante", "Lieblingstante. Ohne Pflichten, mit Gummibärchen.", "kleine Tüte Gummibärchen mit Herz",
         "Neffen und Nichten, die ihre Lieblingstante feiern", "Tante", "Rosa, Gelb"),
        ("Lieblingsonkel", "Onkel: Witze ohne Verfallsdatum.", "kleiner Blitz mit Sprechblase",
         "Neffen und Nichten, die ihren Lieblingsonkel feiern", "Onkel", "Blau, Orange"),
        ("Cousin-Komplize", "Cousin: Komplize seit dem Sandkasten.", "kleine Sandschaufel mit Stern",
         "Cousins mit gemeinsamer Kindheitsgeschichte", "Cousin", "Gelb, Blau"),
        ("Bruder-Sparring", "Bruder: Kostenloser Sparringspartner.", "kleiner Boxhandschuh mit Herz",
         "Geschwister, die ihren Bruder liebevoll aufziehen", "Bruder", "Rot, Anthrazit"),
        ("Schwester-Kleiderdieb", "Schwester: Beste Freundin, Kleiderdieb.", "kleine Sonnenbrille mit Herz",
         "Schwestern mit Humor über geteilte Kleiderschränke", "Schwester", "Rosa, Türkis"),
        ("Patentante-Verwöhnen", "Patentante: Verwöhnen ohne Erziehungsauftrag.", "kleines Geschenk mit Schleife",
         "Patenkinder und Eltern, die die Patentante feiern", "Patentante", "Rosa, Gold"),
        ("Patenonkel-Spaß", "Patenonkel: Spaß ohne Papierkram.", "kleines Spielzeugauto mit Stern",
         "Patenkinder und Eltern, die den Patenonkel feiern", "Patenonkel", "Blau, Orange"),
        ("Trauzeugen-Wissen", "Trauzeuge: Ich weiß zu viel.", "kleiner Ring mit Schloss",
         "Trauzeugen mit Humor über ihr Insiderwissen", "Trauzeuge", "Gold, Anthrazit"),
    )),
    ("Partnerschaft", (
        ("Ehefrau-Recht", "Ehefrau hat immer recht. Ich übe noch.", "kleiner Daumen nach oben mit Herz",
         "Ehemänner mit Humor über ihre Ehefrau", "Ehefrau", "Rot, Anthrazit"),
        ("Ehemann-Butter", "Mein Mann findet nichts. Nicht mal die Butter.", "kleine Butterdose mit Fragezeichen",
         "Ehefrauen mit Humor über ihren Ehemann", "Ehemann", "Gelb, Rosa"),
        ("Pizza-Liebe", "Liebe ist: Das letzte Stück Pizza abgeben.", "kleines Pizzastück mit Herz",
         "Paare mit Humor über Liebe und Essen", "Pizza Liebe", "Rot, Gelb"),
        ("Bettdecken-Krieg", "Bettdecken-Krieg seit 2015.", "kleine Bettdecke mit Flagge",
         "Paare, die sich nachts die Decke streitig machen", "Paar", "Blau, Rot"),
        ("Schnarch-Liebe", "Mein Schatz schnarcht. Ich liebe ihn trotzdem.", "kleine Säge mit Herz",
         "Partner mit Humor über nächtliches Schnarchen", "Schnarchen", "Rosa, Anthrazit"),
        ("Team-Kompromiss", "Verheiratet: Seit Jahren im Kompromiss.", "kleine Waage mit zwei Herzen",
         "Verheiratete Paare mit Humor über gemeinsame Kompromisse", "Verheiratet", "Rot, Gold"),
        ("Fernbedienungs-Frieden", "Fernbedienung gefunden. Frieden gesichert.", "kleine Fernbedienung mit Friedenszeichen",
         "Paare mit täglichem Streit um die Fernbedienung", "Fernbedienung", "Grün, Anthrazit"),
    )),
    ("Baby & Kinder", (
        ("Kind-Notwehr", "Ich bin so süß, das ist Notwehr.", "kleines Herz mit Schleife",
         "Eltern, die ihr Kind mit einem frechen Spruch anziehen", "Kinder", "Rosa, Gelb"),
        ("Kind-Glück", "Meine Eltern haben Glück gehabt.", "kleiner Stern mit Krone",
         "Eltern, die ihr Kind mit einem frechen Spruch anziehen", "Kinder", "Gelb, Blau"),
        ("Kind-Lebendig", "Ich bin nicht laut. Ich bin lebendig.", "kleine Sprechblase mit Blitz",
         "Eltern lebhafter Kinder mit Humor", "Kinder", "Orange, Blau"),
        ("Kind-Nachtisch", "Ich brauche kein Gemüse. Ich brauche Nachtisch.", "kleines Eis mit Herz",
         "Eltern von Kindern, die Nachtisch bevorzugen", "Kinder", "Rosa, Braun"),
        ("Kind-Sandkasten", "Sandkasten-Boss. Wer stört, wird begraben.", "kleine Sandschaufel mit Krone",
         "Eltern von Kindern im Sandkastenalter mit Humor", "Kinder", "Gelb, Grün"),
        ("Kind-Ausrede", "Ich war das nicht. Es war der Hund.", "kleiner Hund mit Unschuldsmiene",
         "Eltern frecher Kinder mit Humor", "Kinder", "Braun, Gelb"),
    )),
    ("Haustiere", (
        ("Hund-Chef", "Mein Hund glaubt, ich arbeite für ihn.", "kleine Hundepfote mit Krone",
         "Hundehalter mit Humor über das Machtgefüge im Haus", "Hund", "Braun, Orange"),
        ("Katze-Untermieter", "Meine Katze lässt mich hier wohnen.", "kleine Katze auf einem Schlüssel",
         "Katzenhalter mit Humor über die Wohnverhältnisse", "Katze", "Grau, Gelb"),
        ("Hundehaar-Glitzer", "Hundehaare sind mein Glitzer.", "kleiner Hund mit Funkeln",
         "Hundehalter mit Humor über Haare auf der Kleidung", "Hund", "Braun, Gold"),
        ("Hund-Versteht", "Mein Hund versteht mich. Meistens.", "kleiner Hund mit Sprechblase",
         "Hundehalter mit Humor über ihre treue Begleitung", "Hund", "Braun, Grün"),
        ("Gassi-Diplom", "Gassi-Meister mit Beutel-Diplom.", "kleine Hundeleine mit Diplomrolle",
         "Hundehalter mit Humor über tägliche Gassirunden", "Gassi", "Grün, Braun"),
        ("Katze-Haustier", "Ich habe ein Haustier. Es hat mich.", "kleine Katze mit Leine",
         "Katzenhalter mit Humor über das Machtgefüge", "Katze", "Orange, Grau"),
        ("Fisch-Schweigen", "Mein Fisch sagt nichts. Ich mag das.", "kleiner Fisch mit Blase",
         "Aquarienfreunde mit Humor über ihren stillen Mitbewohner", "Fisch", "Blau, Orange"),
        ("Dackel-Klappe", "Dackel: Kurze Beine, große Klappe.", "kleiner Dackel im Profil",
         "Dackelhalter mit Humor über ihren frechen Hund", "Dackel", "Braun, Rot"),
        ("Nachteule-Ideen", "Nachteule: Meine Ideen kommen um drei.", "kleine Eule mit Mond",
         "Nachtmenschen mit Liebe zur Nachteule", "Nachteule", "Gelb, Dunkelblau"),
        ("Pflanzen-Kinder", "Pflanzenmama: Meine Kinder haben Blätter.", "kleine Zimmerpflanze mit Herz",
         "Pflanzenliebhaberinnen mit Humor über ihre Zimmerpflanzen", "Pflanzenmama", "Grün, Rosa"),
    )),
    ("Angeln", (
        ("Angeln-Würmer", "Angeln: Ich ertränke Würmer mit Stil.", "kleiner Wurm mit Sonnenbrille",
         "Angler mit sarkastischem Humor über ihr Hobby", "Angeln", "Rosa, Blau"),
        ("Angeln-Therapie", "Angeln ist billiger als Therapie.", "kleine Angelrute mit Sprechblase",
         "Angler, die am Wasser ihre Ruhe suchen", "Angeln", "Grün, Blau"),
        ("Angeln-Beweis", "Der Fisch war riesig. Beweise? Entkommen.", "kleiner Fisch mit Fluchtweg",
         "Angler mit Humor über Anglerlatein und große Fänge", "Angeln", "Orange, Blau"),
        ("Angeln-Ausrede", "Ich kann nicht. Ich muss angeln.", "kleiner Angelhaken mit Herz",
         "Angler, die für ihr Hobby jede Ausrede finden", "Angeln", "Gelb, Grün"),
        ("Angeln-Null-Fische", "Fünf Stunden angeln. Null Fische. Perfekt.", "kleiner leerer Eimer mit Herz",
         "Angler mit Humor über fangfreie Ausflüge", "Angeln", "Blau, Rot"),
        ("Angeln-Bier", "Ohne Bier beißt hier gar nichts.", "kleines Bierglas neben einer Angelrute",
         "Angler mit Vorliebe für ein kühles Bier am Wasser", "Angeln", "Gold, Blau"),
        ("Angeln-Übertreibung", "Angler lügen nicht. Sie übertreiben präzise.", "kleiner Fisch mit Maßband",
         "Angler mit Humor über Anglerlatein", "Angeln", "Grün, Orange"),
        ("Angeln-Homeoffice", "Der See ist mein Homeoffice.", "kleiner Steg mit Angelrute",
         "Angler, die am liebsten am See arbeiten würden", "Angeln", "Blau, Braun"),
        ("Angeln-Seele", "Wurm ins Wasser, Seele baumeln.", "kleiner Schwimmer mit Wellen",
         "Angler, die am Wasser abschalten", "Angeln", "Rot, Blau"),
        ("Angeln-Beißen", "Ich beiße nicht. Die Fische auch nicht.", "kleiner Fisch mit Fragezeichen",
         "Angler mit trockenem Humor über leere Haken", "Angeln", "Grün, Gelb"),
        ("Angeln-Sonnenbrand", "Nichts gefangen. Außer Sonnenbrand.", "kleine Sonne mit Angelhaken",
         "Angler mit Selbstironie nach einem langen Tag am Wasser", "Angeln", "Orange, Rot"),
        ("Angeln-Petri", "Petri Heil und viel Geduld.", "kleiner Fisch mit Heiligenschein",
         "Angler, die sich gegenseitig Petri Heil wünschen", "Angeln", "Gold, Blau"),
    )),
    ("Grillen", (
        ("Grillen-Feuerwehr", "Ich grille. Die Feuerwehr wartet schon.", "kleine Flamme mit Feuerlöscher",
         "Grillmeister mit Humor über ihre Flammen", "Grillen", "Rot, Orange"),
        ("Grillen-Medium", "Schwarz ist das neue Medium.", "kleine verkohlte Wurst",
         "Grillfans, die es gern gut durch mögen", "Grillen", "Braun, Orange"),
        ("Grillen-Gargrad", "Verbrannt ist auch ein Gargrad.", "kleine schwarze Wurst mit Herz",
         "Grillmeister mit Selbstironie über verbranntes Grillgut", "Grillen", "Rot, Anthrazit"),
        ("Grillen-Chaos", "Bier links, Wurst rechts, Chaos mittig.", "kleiner Grillrost mit Bierglas",
         "Grillfreunde mit Sinn für gemütliches Chaos", "Grillen", "Gold, Rot"),
        ("Grillen-Roh", "Ohne mich wäre Wurst nur roh.", "kleine Wurst mit Krone",
         "Grillmeister mit großem Selbstbewusstsein", "Grillen", "Rot, Gelb"),
        ("Grillen-Hunger", "Grillmeister: Hunger kann man erziehen.", "kleine Grillzange mit Uhr",
         "Grillmeister, die ihre hungrigen Gäste warten lassen", "Grillen", "Orange, Braun"),
        ("Grillen-Nachbarn", "Ich grille. Die Nachbarn husten.", "kleine Rauchwolke mit Wurst",
         "Grillmeister mit Humor über Rauchschwaden", "Grillen", "Grau, Rot"),
        ("Grillen-Temperatur", "Wenn es brennt, stimmt die Temperatur.", "kleine Flamme mit Thermometer",
         "Grillmeister mit lockerem Verhältnis zur Hitze", "Grillen", "Rot, Gelb"),
        ("Grillen-Wenden", "Wurst wenden ist mein Sport.", "kleine Grillzange mit Medaille",
         "Grillfans mit Humor über ihr Lieblingshobby", "Grillen", "Gold, Braun"),
        ("Grillen-Salat", "Salat? Nur als Deko neben der Wurst.", "kleines Salatblatt neben einer Wurst",
         "Fleischfans mit Humor über Beilagen", "Grillen", "Grün, Rot"),
        ("Grillen-Anzünden", "Anzünden, angeben, anbrennen lassen.", "kleine Streichholzflamme mit Krone",
         "Grillmeister mit Sinn für große Auftritte", "Grillen", "Orange, Anthrazit"),
        ("Grillen-Chef", "Beim Grillen bin ich der Chef.", "kleine Grillschürze mit Flamme",
         "Grillmeister, die am Rost das Sagen haben", "Grillen", "Rot, Braun"),
    )),
    ("Wandern", (
        ("Wandern-Sinn", "Freiwillig Berge hochlaufen. Wofür eigentlich?", "kleiner Berg mit Fragezeichen",
         "Wanderer mit sarkastischem Humor über ihr Hobby", "Wandern", "Grün, Blau"),
        ("Wandern-Kuchen", "Ich wandere nur, wenn es Kuchen gibt.", "kleines Kuchenstück auf einem Gipfel",
         "Genusswanderer mit Vorliebe für Kuchen am Gipfel", "Wandern", "Braun, Grün"),
        ("Wandern-Wegweiser", "Noch fünf Minuten, sagte der Wegweiser.", "kleiner Wegweiser mit Schweißtropfen",
         "Wanderer mit Humor über optimistische Wegweiser", "Wandern", "Braun, Orange"),
        ("Wandern-Schimpfen", "Bergauf schimpfen, oben grinsen.", "kleiner Berg mit Sonne",
         "Wanderer, die den Aufstieg verfluchen und den Gipfel lieben", "Wandern", "Grün, Gelb"),
        ("Wandern-Brotzeit", "Warum ich wandere? Wegen der Brotzeit.", "kleine Brezel vor einem Berggipfel",
         "Wanderer, die sich auf die Brotzeit freuen", "Wandern", "Braun, Blau"),
        ("Wandern-Hütte", "Gipfelstürmer. Zumindest bis zur Hütte.", "kleine Berghütte mit Fahne",
         "Wanderer, die es bis zur Hütte schaffen", "Wandern", "Rot, Grün"),
        ("Wandern-Blasen", "Ich habe Blasen. Und Aussicht.", "kleines Pflaster vor einem Bergpanorama",
         "Wanderer mit Humor über schmerzende Füße", "Wandern", "Rosa, Grün"),
        ("Wandern-Netz", "Kein Netz. Perfekt.", "kleines durchgestrichenes Handy vor einem Berg",
         "Wanderer, die den Handyempfang im Gebirge genießen", "Wandern", "Blau, Grün"),
        ("Wandern-Hüttenlust", "Wanderlust? Eher Hüttenlust.", "kleine Hütte mit Herz",
         "Wanderer mit Vorliebe für Hüttenabende", "Wandern", "Braun, Rot"),
        ("Wandern-Knie", "Bergab sind meine Knie Diva.", "kleines Knie mit Krone",
         "Wanderer mit Humor über strapazierte Knie", "Wandern", "Rosa, Grau"),
        ("Wandern-Verlaufen", "Ich verlaufe mich nur mit Stil.", "kleine Karte mit Fragezeichen",
         "Wanderer mit Humor über verpasste Abzweigungen", "Wandern", "Grün, Orange"),
        ("Wandern-Sport", "Ohne Kuchen ist es nur Sport.", "kleiner Wanderschuh mit Kuchenstück",
         "Wanderer, die Kuchen zum Wandern brauchen", "Wandern", "Braun, Gelb"),
    )),
    ("Camping", (
        ("Camping-Regen", "Camping: Ich zahle für Regen im Zelt.", "kleines Zelt mit Regenwolke",
         "Camper mit Humor über Regen im Urlaub", "Camping", "Grün, Blau"),
        ("Camping-Ehe", "Zelt aufgebaut. Ehe getestet.", "kleines Zelt mit zwei Herzen",
         "Camper-Paare mit Humor über den gemeinsamen Zeltaufbau", "Camping", "Rot, Grün"),
        ("Camping-Klo", "Camping: Freiwillig ohne Klo leben.", "kleines Zelt mit Sorgenfalte",
         "Camper mit Selbstironie über fehlenden Komfort", "Camping", "Braun, Grün"),
        ("Camping-Wlan", "Kein Wlan. Endlich Familie.", "kleines Lagerfeuer mit Sternen",
         "Camper-Familien, die das Handy im Zelt lassen", "Camping", "Orange, Blau"),
        ("Camping-Lagerfeuer", "Lagerfeuer: Fernsehen für Naturfans.", "kleines Lagerfeuer mit Funken",
         "Camper, die abends am Feuer sitzen", "Camping", "Orange, Rot"),
        ("Camping-Mücken", "Mücken lieben mich. Ich sie nicht.", "kleine Mücke mit Herz",
         "Camper mit Humor über Mückenstiche", "Camping", "Rot, Grün"),
        ("Camping-Mückenparty", "Ich campe. Die Mücken feiern mit.", "kleine Mücke mit Partyhut",
         "Camper mit Humor über ungebetene Gäste", "Camping", "Gelb, Grün"),
        ("Camping-Zeltaufbau", "Zeltaufbau: Der Beziehungstest für Camper.", "kleine Zeltstangen mit Blitz",
         "Camper-Paare mit Humor über Zeltaufbau-Streit", "Camping", "Blau, Orange"),
        ("Camping-Dosenravioli", "Dosenravioli: Meine Campingküche mit Stern.", "kleine Konservendose mit Stern",
         "Camper mit Humor über einfache Küche", "Camping", "Rot, Gold"),
        ("Camping-Frieren", "Draußen schlafen, drinnen frieren.", "kleiner Eiszapfen vor einem Zelt",
         "Camper mit Humor über kalte Nächte", "Camping", "Blau, Grau"),
        ("Camping-Boden", "Ich schlafe freiwillig auf dem Boden.", "kleine Isomatte mit Fragezeichen",
         "Camper mit Selbstironie über ihr Schlaflager", "Camping", "Grün, Gelb"),
        ("Camping-Klapp", "Klapptisch, Klappstuhl, klappernde Zähne.", "kleiner Klappstuhl mit Schneeflocke",
         "Camper mit Humor über kühle Abende", "Camping", "Blau, Orange"),
    )),
    ("Getränke", (
        ("Bier-Persönlichkeit", "Bier: Flüssiges Brot mit Persönlichkeit.", "kleines Bierglas mit Schaumkrone",
         "Bierfreunde mit Humor über ihr Lieblingsgetränk", "Bier", "Gold, Braun"),
        ("Wein-Solidarität", "Ich trinke Wein. Aus Solidarität mit den Trauben.", "kleine Traube mit Weinglas",
         "Weinfreunde mit Humor über ihre Weinliebe", "Wein", "Rot, Grün"),
        ("Tee-Honig", "Tee: Weil Anschreien keine Option ist.", "kleine Teetasse mit Honiglöffel",
         "Teetrinker mit Humor über ihre Ruhepause", "Tee", "Gelb, Grün"),
        ("Spritz-Verein", "Spritz-Verein: Mitglied auf Lebenszeit.", "kleines Spritzglas mit Orangenscheibe",
         "Spritz-Fans mit Humor über ihre Lieblingsrunde", "Spritz", "Orange, Grün"),
        ("Glühwein-Winter", "Glühwein: Nach drei Tassen ist Winter warm.", "kleine Tasse mit Dampf und Stern",
         "Weihnachtsmarkt-Besucher mit Humor über Winterabende", "Glühwein", "Rot, Gold"),
        ("Prosecco-Probleme", "Prosecco statt Probleme.", "kleines Sektglas mit Blasen",
         "Sektfans mit Humor über kleine Sorgen", "Prosecco", "Gold, Rosa"),
    )),
    ("Anlässe", (
        ("Geburtstag-Reif", "Alt werden ist Pflicht. Reif werden optional.", "kleine Kerze mit Fragezeichen",
         "Geburtstagskinder mit Humor über das Altwerden", "Geburtstag", "Gold, Rot"),
        ("Geburtstag-Kuchen", "Ich habe Geburtstag. Ihr habt Kuchen.", "kleines Kuchenstück mit Kerze",
         "Geburtstagskinder mit Vorfreude auf Kuchen", "Geburtstag", "Rosa, Gelb"),
        ("Dreißig-Rücken", "30: Kind im Herzen, Rücken im Keller.", "kleine Zahl 30 mit Pflaster",
         "Dreißigjährige mit Humor über das Alter", "30 Geburtstag", "Blau, Orange"),
        ("Vierzig-Humor", "40: Neuer Rücken, alter Humor.", "kleine Zahl 40 mit Stern",
         "Vierzigjährige mit Humor über das Alter", "40 Geburtstag", "Rot, Gold"),
        ("Fünfzig-Erfahrung", "50 Jahre Erfahrung. Keine Garantie.", "kleine Zahl 50 mit Siegel",
         "Fünfzigjährige mit Humor über das Alter", "50 Geburtstag", "Gold, Anthrazit"),
        ("Weihnachten-Kekse", "Weihnachten: Zeit für Kekse und Chaos.", "kleine Zuckerstange mit Stern",
         "Familien mit Humor über das Weihnachtsfest", "Weihnachten", "Rot, Grün"),
        ("Silvester-Vorsatz", "Silvester: Vorsätze bis 0:01 Uhr.", "kleine Rakete mit Uhr",
         "Feiernde mit Humor über gute Vorsätze", "Silvester", "Gold, Blau"),
        ("Ostern-Eiersuche", "Ostern: Ich suche Eier. Und Nerven.", "kleines Osterei mit Hase",
         "Familien mit Humor über das Osterfest", "Ostern", "Gelb, Grün"),
        ("Fasching-Vernunft", "Fasching: Verkleidet als vernünftiger Erwachsener.", "kleine Narrenkappe mit Fragezeichen",
         "Faschingsfans mit Humor über ihre Verkleidung", "Fasching", "Rot, Gelb"),
        ("JGA-Amnesie", "JGA-Team: Wir wissen von nichts.", "kleiner Schleier mit Fragezeichen",
         "Junggesellenabschied-Gruppen mit Humor über verschwiegene Abende", "JGA", "Rosa, Gold"),
        ("Braut-Sekt", "Braut-Team: Sekt statt Sorgen.", "kleines Sektglas mit Ring",
         "Braut-Teams beim Junggesellenabschied", "Braut", "Rosa, Gold"),
        ("Vatertag-Bollerwagen", "Vatertag: Bollerwagen-Betrieb gestartet.", "kleiner Bollerwagen mit Fahne",
         "Väter und Freunde am Vatertag", "Vatertag", "Grün, Braun"),
    )),
    ("Sternzeichen", (
        ("Widder-Denken", "Widder: Erst handeln, dann denken.", "kleiner Widderkopf mit Blitz",
         "Widder-Geborene mit Humor über ihr Sternzeichen", "Widder", "Rot, Anthrazit"),
        ("Stier-Basta", "Stier: Ich bewege mich nicht. Basta.", "kleiner Stierkopf mit Ringen",
         "Stier-Geborene mit Humor über ihre Sturheit", "Stier", "Grün, Braun"),
        ("Zwillinge-Ausrede", "Zwillinge: Zwei Meinungen, eine Ausrede.", "kleine zwei Sterne mit Sprechblasen",
         "Zwillinge-Geborene mit Humor über ihre Zwiespältigkeit", "Zwillinge", "Gelb, Blau"),
        ("Krebs-Kuschelkern", "Krebs: Harte Schale, Kuschelkern.", "kleiner Krebs mit Herz",
         "Krebs-Geborene mit Humor über ihr Sternzeichen", "Krebs", "Rosa, Blau"),
        ("Löwe-Eitel", "Löwe: Ich bin nicht eitel. Ich bin schön.", "kleine Löwenmähne mit Krone",
         "Löwe-Geborene mit Humor über ihr Selbstbewusstsein", "Löwe", "Gold, Orange"),
        ("Jungfrau-Sortieren", "Jungfrau: Ich sortiere sogar Gefühle.", "kleines Etikett mit Herz",
         "Jungfrau-Geborene mit Humor über ihre Ordnungsliebe", "Jungfrau", "Grün, Anthrazit"),
        ("Waage-Später", "Waage: Ich entscheide mich später.", "kleine Waage mit Fragezeichen",
         "Waage-Geborene mit Humor über ihre Entscheidungsfreude", "Waage", "Rosa, Blau"),
        ("Skorpion-Gedächtnis", "Skorpion: Ich merke mir alles. Alles.", "kleiner Skorpion mit Notizbuch",
         "Skorpion-Geborene mit Humor über ihr Gedächtnis", "Skorpion", "Rot, Anthrazit"),
        ("Schütze-Flieger", "Schütze: Wo ist der Flieger?", "kleiner Pfeil mit Flugzeug",
         "Schütze-Geborene mit Humor über ihre Reiselust", "Schütze", "Orange, Blau"),
        ("Steinbock-Arbeit", "Steinbock: Arbeit ist mein Hobby.", "kleiner Steinbock mit Aktentasche",
         "Steinbock-Geborene mit Humor über ihren Fleiß", "Steinbock", "Braun, Anthrazit"),
        ("Wassermann-Anders", "Wassermann: Ich bin anders. Mit Absicht.", "kleine Welle mit Stern",
         "Wassermann-Geborene mit Humor über ihre Eigenart", "Wassermann", "Türkis, Blau"),
        ("Fische-Wegschwimmen", "Fische: Ich fühle. Und schwimme weg.", "kleiner Fisch mit Herz",
         "Fische-Geborene mit Humor über ihre Sensibilität", "Fische", "Blau, Rosa"),
    )),
    ("Regional", (
        ("Nord-Moin", "Moin reicht als Gespräch.", "kleiner Anker mit Möwe",
         "Norddeutsche mit Humor über ihre knappe Sprache", "Moin Norddeutschland", "Blau, Rot"),
        ("Berliner-Schnauze", "Berliner Schnauze, weiches Herz.", "kleines Herz mit Sprechblase",
         "Berliner mit Humor über ihren Charakter", "Berlin", "Rot, Anthrazit"),
        ("Schwabe-Sparen", "Schwabe: Ich spare, also bin ich.", "kleine Münze mit Kehrwoche-Besen",
         "Schwaben mit Humor über ihre Sparsamkeit", "Schwabe", "Gold, Blau"),
        ("Bayern-Grantler", "Ich grantle nicht. Ich informiere.", "kleine Brezel mit Herz",
         "Bayern mit Humor über ihren Grant", "Bayern", "Blau, Braun"),
        ("Ruhrpott-Ehrlich", "Ruhrpott: Wir sagen es dir ins Gesicht.", "kleines Herz mit Förderturm",
         "Menschen aus dem Ruhrgebiet mit Humor über ihre Direktheit", "Ruhrpott", "Anthrazit, Gelb"),
        ("Hamburg-Regen", "Hamburg: Sonne ist nur ein Gerücht.", "kleine Regenwolke mit Anker",
         "Hamburger mit Humor über das Wetter", "Hamburg", "Blau, Rot"),
    )),
    ("Nerd & Technik", (
        ("Nerd-Rechner", "Läuft bei mir. Also nur auf meinem Rechner.", "kleiner Monitor mit Daumen",
         "IT-Fans mit Humor über Programmierer-Ausreden", "Nerd", "Grün, Anthrazit"),
        ("Nerd-Backup", "Backup gemacht? Ich glaube schon.", "kleine Festplatte mit Fragezeichen",
         "IT-Fans mit Humor über Datensicherung", "Nerd", "Blau, Orange"),
        ("Nerd-Automatisieren", "Ich bin nicht faul. Ich automatisiere.", "kleiner Zahnradkranz mit Herz",
         "IT-Fans mit Humor über ihre Automatisierung", "Nerd", "Grün, Anthrazit"),
        ("Nerd-404", "Fehler 404: Ausrede nicht gefunden.", "kleines Warndreieck mit Bildschirm",
         "IT-Fans mit Humor über fehlende Ausreden", "Nerd", "Blau, Rot"),
        ("Nerd-Kaffee", "Ladebalken: Kaffee bei 87 Prozent.", "kleine Kaffeetasse mit Ladebalken",
         "Berufstätige, die ihren Kaffeestand an Ladebalken messen", "Kaffee", "Braun, Grün"),
    )),
    ("Studium & Musik", (
        ("Studium-Prokrastination", "Studium: Prokrastination mit Vorlesungszeit.", "kleines Buch mit Uhr",
         "Studierende mit Humor über das Aufschieben", "Studium", "Blau, Orange"),
        ("Klausur-Kaffee", "Klausurphase: Kaffee mit Nervenzusammenbruch.", "kleiner Kaffeebecher mit Blitz",
         "Studierende mit Humor über die Klausurphase", "Klausur", "Braun, Rot"),
        ("Dusche-Konzert", "Ich singe unter der Dusche. Nachbarn leiden.", "kleine Duschbrause mit Musiknote",
         "Hobbysänger mit Humor über ihre Duschkonzerte", "Musik", "Blau, Gelb"),
        ("Kopfhörer-Welt", "Kopfhörer auf, Welt aus.", "kleine Kopfhörer mit Musiknote",
         "Musikfans mit Humor über ihren Rückzug", "Kopfhörer", "Rot, Anthrazit"),
        ("Gitarre-Ego", "Gitarre: Vier Akkorde, ein Ego.", "kleine Gitarre mit Krone",
         "Hobbygitarristen mit Humor über ihr Selbstbild", "Gitarre", "Orange, Braun"),
    )),
    ("Reise & Haushalt", (
        ("Urlaub-Vom-Urlaub", "Ich brauche Urlaub vom Urlaub.", "kleiner Koffer mit Sonnenbrille",
         "Erholungsbedürftige Reisende mit Humor", "Urlaub", "Türkis, Gelb"),
        ("Strand-Büro", "Mein Büro hat Meerblick. Manchmal.", "kleine Palme mit Laptop",
         "Fernweh-Geplagte mit Humor über ihr Büro", "Strand", "Türkis, Grün"),
        ("Urlaub-Modus", "Urlaubsmodus: Mail? Nie gehört.", "kleine Sonne mit durchgestrichenem Briefumschlag",
         "Urlauber mit Humor über ihre Erreichbarkeit", "Urlaub", "Gelb, Blau"),
        ("Stau-Wohnzimmer", "Stau: Mein zweites Wohnzimmer.", "kleines Auto mit Sofa",
         "Pendler mit Humor über tägliche Staus", "Stau", "Rot, Anthrazit"),
        ("Zug-Ausfall", "Zug fällt aus. Ich auch.", "kleiner Zug mit Fragezeichen",
         "Pendler mit Humor über Verspätungen", "Pendler", "Rot, Anthrazit"),
        ("Navi-Kaffee", "Navi sagt links. Ich sage Kaffee.", "kleine Landkarte mit Kaffeetasse",
         "Autofahrer mit Humor über Umwege", "Navi", "Braun, Blau"),
        ("Socken-Waschmaschine", "Socke verloren. Waschmaschine, gestehe!", "kleine Socke mit Fragezeichen",
         "Haushaltsgeplagte mit Humor über verlorene Socken", "Socken", "Blau, Gelb"),
        ("Spülmaschine-Sport", "Spülmaschine ausräumen: Der wahre Sport.", "kleiner Teller mit Medaille",
         "Haushaltsgeplagte mit Humor über tägliche Pflichten", "Haushalt", "Blau, Gold"),
        ("Sneaker-Platz", "Sneaker-Sammler: Platz ist relativ.", "kleiner Sneaker mit Stern",
         "Sneaker-Fans mit Humor über ihre Sammlung", "Sneaker", "Rot, Orange"),
        ("Kleiderschrank-Leer", "Kleiderschrank voll. Nichts anzuziehen.", "kleine Motte mit Fragezeichen",
         "Modebegeisterte mit Humor über ihren Kleiderschrank", "Kleiderschrank", "Rosa, Anthrazit"),
    )),
)

#: Zaehlt die Eintraege, ohne sie zu bauen.
ANZAHL = sum(len(eintraege_) for _, eintraege_ in _GRUPPEN)


def _bauen(gruppe: str, e: _Eintrag) -> trends.Trend:
    thema, spruch, motiv, ziel, suchwort, farben = e
    return trends.Trend(
        thema=thema, kategorie=KATEGORIE, warum=_WARUM, zeitraum=_ZEITRAUM,
        zielgruppe=ziel, kaufmoment=_KAUFMOMENT,
        verkaufswinkel=f"Überraschende Pointe zum Thema {suchwort} statt eines austauschbaren Standardspruchs",
        motiv=(f"{motiv[:1].upper()}{motiv[1:]}, schlicht gezeichnet, sehr klein unter dem "
               "Schriftzug platziert, freigestellt, ohne Weiss."),
        stil=_STIL, farben=[f.strip() for f in farben.split(",")], spruch=spruch,
        produkt=_PRODUKT, druckhinweis=_DRUCK, risiko=_RISIKO,
        suchbegriffe=[f"{suchwort} Shirt lustig", f"{suchwort} T-Shirt Spruch",
                      f"Geschenk {suchwort} lustig"],
        quellen=[], gruppe=gruppe)


def eintraege() -> list[trends.Trend]:
    return [_bauen(gruppe, e) for gruppe, liste in _GRUPPEN for e in liste]


def lade(db: Any, *, filter_check: Callable[[str], Any] | None = None,
         heute: date | None = None) -> dict:
    """Kollektion als Empfehlungen ablegen. Kostenlos; mehrfaches Laden verdoppelt nichts."""
    bericht = trends.speichere(
        db, eintraege(), belege=[], angebote={},
        filter_check=filter_check or trends._schutzfilter_check,
        heute=heute or date.today(), erwartete_kategorie=KATEGORIE)
    bericht["kosten_usd"] = 0.0
    return bericht
